services:
    app.repository.zipcode:
        class: AppBundle\Repository\ZipCodeRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments: ['AppBundle\Entity\ZipCode']
        public: true

    app.repository.contact:
        class: AppBundle\Repository\ContactRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments: ['AppBundle\Entity\Contact']
        public: true